[build]
  command = "npm run export"
  publish = "out"

[[redirects]]
  from = "/job-tracker/*"
  to = "/job-tracker/index.html"
  status = 200

[[redirects]]
  from = "/job-tracker"
  to = "/job-tracker/"
  status = 301 